EXAMPLE_SLUG = 'test-slug'
EXAMPLE_USERNAME = 'auth'
EXAMPLE_USERNAME_1 = 'auth1'
EXAMPLE_TEXT = 'Тестовый пост'
EXAMPLE_TEXT_1 = 'Тестовый пост 1'
EXAMPLE_TITLE = 'Тестовый заголовок'
EXAMPLE_DESCRIPTION = 'Тестовое описание'

INDEX_URL = 'posts:index'
GROUP_LIST_URL = 'posts:group_list'
PROFILE_URL = 'posts:profile'
POST_DETAIL_URL = 'posts:post_detail'
POST_EDIT_URL = 'posts:post_edit'
POST_CREATE_URL = 'posts:post_create'

INDEX_TEMPLATE = 'posts/index.html'
GROUP_LIST_TEMPLATE = 'posts/group_list.html'
PROFILE_TEMPLATE = 'posts/profile.html'
POST_DETAIL_TEMPLATE = 'posts/post_detail.html'
POST_CREATE_TEMPLATE = 'posts/post_create.html'
